apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo
  namespace: rollouts-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
    spec:
      containers:
      - name: app
        image: nginx:1.25
        ports:
        - containerPort: 80

  strategy:
    canary:
      analysis:
        templates:
        - templateName: success-rate-check
      steps:
      - setWeight: 20
      - pause:
          duration: "30s"
      - setWeight: 50
      - pause:
          duration: "30s"
      - setWeight: 100

